// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/gossip/pb/gossip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry is a single versioned key-value pair.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_internal_gossip_pb_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_pb_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_internal_gossip_pb_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Entry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// EntryBatch is used for both broadcast messages and anti-entropy snapshots.
type EntryBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryBatch) Reset() {
	*x = EntryBatch{}
	mi := &file_internal_gossip_pb_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryBatch) ProtoMessage() {}

func (x *EntryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_pb_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryBatch.ProtoReflect.Descriptor instead.
func (*EntryBatch) Descriptor() ([]byte, []int) {
	return file_internal_gossip_pb_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *EntryBatch) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// NodeMeta carries per-node metadata encoded in memberlist's Meta field.
type NodeMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedisAddr     string                 `protobuf:"bytes,1,opt,name=redis_addr,json=redisAddr,proto3" json:"redis_addr,omitempty"` // e.g. "10.0.0.1:6379"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMeta) Reset() {
	*x = NodeMeta{}
	mi := &file_internal_gossip_pb_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMeta) ProtoMessage() {}

func (x *NodeMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_gossip_pb_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMeta.ProtoReflect.Descriptor instead.
func (*NodeMeta) Descriptor() ([]byte, []int) {
	return file_internal_gossip_pb_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *NodeMeta) GetRedisAddr() string {
	if x != nil {
		return x.RedisAddr
	}
	return ""
}

var File_internal_gossip_pb_gossip_proto protoreflect.FileDescriptor

const file_internal_gossip_pb_gossip_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/gossip/pb/gossip.proto\x12\x06gossip\"I\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"5\n" +
	"\n" +
	"EntryBatch\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.gossip.EntryR\aentries\")\n" +
	"\bNodeMeta\x12\x1d\n" +
	"\n" +
	"redis_addr\x18\x01 \x01(\tR\tredisAddrB:Z8github.com/peacewalker122/hapartition/internal/gossip/pbb\x06proto3"

var (
	file_internal_gossip_pb_gossip_proto_rawDescOnce sync.Once
	file_internal_gossip_pb_gossip_proto_rawDescData []byte
)

func file_internal_gossip_pb_gossip_proto_rawDescGZIP() []byte {
	file_internal_gossip_pb_gossip_proto_rawDescOnce.Do(func() {
		file_internal_gossip_pb_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_gossip_pb_gossip_proto_rawDesc), len(file_internal_gossip_pb_gossip_proto_rawDesc)))
	})
	return file_internal_gossip_pb_gossip_proto_rawDescData
}

var file_internal_gossip_pb_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_gossip_pb_gossip_proto_goTypes = []any{
	(*Entry)(nil),      // 0: gossip.Entry
	(*EntryBatch)(nil), // 1: gossip.EntryBatch
	(*NodeMeta)(nil),   // 2: gossip.NodeMeta
}
var file_internal_gossip_pb_gossip_proto_depIdxs = []int32{
	0, // 0: gossip.EntryBatch.entries:type_name -> gossip.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_gossip_pb_gossip_proto_init() }
func file_internal_gossip_pb_gossip_proto_init() {
	if File_internal_gossip_pb_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_gossip_pb_gossip_proto_rawDesc), len(file_internal_gossip_pb_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_gossip_pb_gossip_proto_goTypes,
		DependencyIndexes: file_internal_gossip_pb_gossip_proto_depIdxs,
		MessageInfos:      file_internal_gossip_pb_gossip_proto_msgTypes,
	}.Build()
	File_internal_gossip_pb_gossip_proto = out.File
	file_internal_gossip_pb_gossip_proto_goTypes = nil
	file_internal_gossip_pb_gossip_proto_depIdxs = nil
}
