apiVersion: v1
kind: Pod
metadata:
  name: hapartition
  namespace: hapartition
  labels:
    app: hapartition
spec:
  containers:
    - name: hapartition
      image: ghcr.io/peacewalker122/hapartition:latest
      ports:
        - containerPort: 6379
          name: redis
        - containerPort: 8080
          name: http
        - containerPort: 7946
          name: gossip
